/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import JDBC.MarcaJDBC;
import JDBC.ProductoJDBC;
import JDBC.ProveedorJDBC;
import POJO.MarcaPOJO;
import POJO.ProductoPOJO;
import POJO.ProveedorPOJO;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.github.sarxos.webcam.WebcamUtils;
import com.github.sarxos.webcam.util.ImageUtils;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author aaron
 */
public class AgregarProducto extends javax.swing.JFrame {

    JButton botonPres;
    JFrame padre2;
    JFrame menu2;
    Connection con;
    Connection con1;
    Statement st;
    Statement st1;
    ResultSet rs;
    ResultSet rs1;
    private Statement instruccion;
    private ResultSet conjuntoResultados;
    boolean sePuede = false;
    Productos producto2;
    Webcam webcam = Webcam.getDefault();
    WebcamPanel panel = new WebcamPanel(webcam, new Dimension(150, 150), false);

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
        conjuntoResultados = null;
        instruccion = null;
    }

    public AgregarProducto(JButton boton, JFrame padre, JFrame menu, Productos producto) {
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        setOpacity(0);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        jToolBar1.setFloatable(false);
        setLocationRelativeTo(null);
        jTextField1.setEnabled(false);
        jComboBox1.removeAllItems();
        jComboBox1.setModel(ProductoJDBC.cargarCombo());
        jComboBox2.removeAllItems();
        jComboBox2.setModel(ProveedorJDBC.cargarCombo());
        sePuede = true;
        botonPres = boton;
        padre2 = padre;
        menu2 = menu;
        producto2 = producto;
        generarCamara();
    }
    
    public void generarCamara(){
        webcam.setViewSize(WebcamResolution.VGA.getSize());
        panel.setFillArea(true);
        panel.setFPSDisplayed(true);
        panel.setDisplayDebugInfo(true);
        panel.setImageSizeDisplayed(true);
        panel.setMirrored(true);
        jPanel1.removeAll();
        jPanel1.setLayout(new FlowLayout());
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnIniciaCamara = new javax.swing.JButton();
        btnTomarFoto = new javax.swing.JButton();
        btnTomarFotos = new javax.swing.JButton();
        btnRepetir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 692));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("No. de identificación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel3.setText("Marca");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel4.setText("Proveedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel5.setText("Precio de venta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 210, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 280, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 280, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 210, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 280, -1));

        jCheckBox1.setText("Nueva");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel6.setText("Características");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 280, 100));

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/salida.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clearazul32.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, 150));

        btnIniciaCamara.setText("jButton4");
        btnIniciaCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaCamaraActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciaCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 40, -1));

        btnTomarFoto.setText("jButton4");
        btnTomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 40, -1));

        btnTomarFotos.setText("jButton4");
        getContentPane().add(btnTomarFotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 40, -1));

        btnRepetir.setText("jButton4");
        btnRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepetirActionPerformed(evt);
            }
        });
        getContentPane().add(btnRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 40, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondoAgregar.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Funciones funciones = new Funciones();
        JFrame ventanas[] = {menu2, padre2};
        funciones.Desaparecer(this, ventanas);
        producto2.estadoBotones();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numeroIdentificacion = jTextField2.getText();
        double precioVenta = Double.parseDouble(jFormattedTextField1.getText());
        int idProveedor = jComboBox2.getSelectedIndex();
        String caracteristica = jTextArea1.getText();
        int idMarca = jComboBox1.getSelectedIndex();
        if (jCheckBox1.isSelected()) {
            MarcaPOJO marcaPOJO = new MarcaPOJO();
            marcaPOJO.setNombre(jTextField1.getText());
            idMarca = MarcaJDBC.insertar(marcaPOJO);
            if (idMarca != 0) {
                System.out.println("Nueva Marca Guardada");
                jComboBox1.setModel(ProductoJDBC.cargarCombo());
            } else {
                System.out.println("Nueva marca no guardada");
            }
        } else {
            idMarca = jComboBox1.getSelectedIndex();
        }
        ProductoPOJO productoPOJO = new ProductoPOJO();
        productoPOJO.setMarca_idMarca(idMarca);
        productoPOJO.setProveedores_idProveedores(idProveedor);
        productoPOJO.setNumeroIdentificacion(numeroIdentificacion);
        productoPOJO.setCaracteristica(caracteristica);
        productoPOJO.setPrecioventa(precioVenta);
        productoPOJO.setExistente(true);
        productoPOJO.setImagen("imagenes/"+jTextField2.getText()+".png");
        
        int x = ProductoJDBC.insertar(productoPOJO);

        if (x != 0) {
            JOptionPane.showMessageDialog(null, "Guardado");
            producto2.cargarTree();
            jCheckBox1.setSelected(false);
            jComboBox1.setEnabled(true);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jTextArea1.setText("");
            jTextField1.setEnabled(false);
            jTextField1.setText("");
            jTextField2.setText("");
            jFormattedTextField1.setText("");
            generarCamara();
        } else {
            JOptionPane.showMessageDialog(null, "CATASTROPHIC ERROR");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEnabled(false);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jFormattedTextField1.setText(null);
        jTextArea1.setText(null);
        jCheckBox1.setSelected(false);
        jComboBox1.setEnabled(true);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jTextField1.setEnabled(true);
            jComboBox1.setEnabled(false);
        } else {
            jTextField1.setEnabled(false);
            jComboBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void btnIniciaCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaCamaraActionPerformed
        // TODO add your handling code here:
        generarCamara();
        panel.start();
    }//GEN-LAST:event_btnIniciaCamaraActionPerformed

    private void btnTomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarFotoActionPerformed
        // TODO add your handling code here:
        File file = new File("imagenes");
        if (!file.exists()) {
            if (file.mkdir()) {
                System.out.println("Directorio creado");
            } else {
                System.out.println("Directorio no creado");
            }
        } else {
            System.out.println("Directorio ya existente");
        }
        WebcamUtils.capture(webcam, file+"\\"+jTextField2.getText(), ImageUtils.FORMAT_PNG);
        panel.stop();
        jPanel1.removeAll();
        ImageIcon imageIcon = new ImageIcon("imagenes/"+jTextField2.getText()+".png");
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(jPanel1.getWidth(), jPanel1.getHeight(), Image.SCALE_DEFAULT));
        JLabel jLabel = new JLabel();
        jLabel.setSize(150, 150);
        jLabel.setIcon(icon);
        jPanel1.add(jLabel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnTomarFotoActionPerformed

    private void btnRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepetirActionPerformed
        // TODO add your handling code here:
        File file = new File("imagenes\\"+jTextField2.getText()+".png");
        file.delete();
        jPanel1.removeAll();
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
        panel.start();
    }//GEN-LAST:event_btnRepetirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciaCamara;
    private javax.swing.JButton btnRepetir;
    private javax.swing.JButton btnTomarFoto;
    private javax.swing.JButton btnTomarFotos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
